# Generated by Django 3.2.4 on 2021-12-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesform',
            old_name='course',
            new_name='message',
        ),
    ]
