# Generated by Django 3.2.4 on 2021-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.JSONField(blank=True),
        ),
    ]
