# Generated by Django 3.2.4 on 2021-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210605_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alt_text',
            field=models.CharField(default='Course - Coden Live', max_length=200),
        ),
    ]
