# Generated by Django 3.2.4 on 2021-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='Arshdeep Singh', max_length=200),
        ),
    ]
