# Generated by Django 3.2.4 on 2021-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_name',
            field=models.CharField(default='Course - Coden Live', max_length=200),
        ),
    ]
