# Generated by Django 3.2.4 on 2021-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
