# Generated by Django 3.2.4 on 2021-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
