# Generated by Django 3.2.4 on 2021-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='job_opportunity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='major_topic_covered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.JSONField(default='[]'),
        ),
        migrations.AddField(
            model_name='course',
            name='who_should_apply',
            field=models.TextField(blank=True),
        ),
    ]
