# Generated by Django 3.2.4 on 2021-07-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210726_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.JSONField(default=[]),
        ),
    ]
