# Generated by Django 3.2.4 on 2021-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.JSONField(blank=True),
        ),
    ]
