name: test
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd pyapps
            source venv/bin/activate
            cd Coden-Live
            git pull
            python manage.py collectstatic --noinput
            python manage.py makemigrations
            python manage.py migrate
            echo ${{ secrets.PW }} | sudo -S -k sudo systemctl restart gunicorn            
            echo ${{ secrets.PW }} | sudo -S -k sudo systemctl restart nginx            
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"