name: test
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir b
            
          host: 165.232.185.199
          user: djangoadmin
          key: ${{ secrets.KEY}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"
