name: CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CD:
    name: Continuous Delivery
    runs-on: Ubuntu 20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          host: 165.232.185.199
          username: djangoadmin
          key: ${{secrets.ID_RSA}}
          port: 80
          script: |
            cd pyapps/Coden-Live
            git pull
            git status
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
